version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: event_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_pipeline
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: event_app
    depends_on:
      - db
    volumes:
      - ./output:/app/output

volumes:
  mysql_data:
